services:
  vllm-gpt-oss:
    image: vllm/vllm-openai@sha256:6766ce0c459e24b76f3e9ba14ffc0442131ef4248c904efdcbf0d89e38be01fe
    runtime: nvidia
    ipc: host
    ulimits:
      memlock: -1
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - hugginface_cache:/root/.cache/huggingface
      - vllm_cache:/root/.cache/vllm
    environment:
      - HF_TOKEN=${HUGGING_FACE_HUB_TOKEN}
      - HF_ENDPOINT=https://huggingface.co
      - VLLM_LOGGING_LEVEL=WARNING
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - NVIDIA_VISIBLE_DEVICES=all
      - VLLM_MXFP4_USE_MARLIN=1
      - VLLM_CACHE_ROOT=/root/.cache/vllm
    command:
      - openai/gpt-oss-120b
      - --revision=b5c939de8f754692c1647ca79fbf85e8c1e70f8a
      - --tensor-parallel-size=1
      - --gpu-memory-utilization=0.95
      - --max-num-seqs=32
      - --max-num-batched-tokens=8192
      - --max-model-len=131072
      - --no-enable-prefix-caching
      - --speculative-config={"method":"eagle3","model":"nvidia/gpt-oss-120b-Eagle3-v2","num_speculative_tokens":3}
      - --async-scheduling
      - --tool-call-parser=openai
      - --enable-auto-tool-choice
      - --enable-prompt-tokens-details
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/v1/models"]
      interval: 30s
      timeout: 10s
      retries: 100
      start_period: 3600s
    restart: unless-stopped

  dcgm-exporter:
    image: nvcr.io/nvidia/k8s/dcgm-exporter:4.5.2-4.8.1-distroless
    container_name: dcgm-exporter
    runtime: nvidia
    cap_add:
      - SYS_ADMIN
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "9400:9400"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    labels:
      com.datadoghq.ad.check_names: '["dcgm"]'
      com.datadoghq.ad.init_configs: "[{}]"
      com.datadoghq.ad.instances: '[{"openmetrics_endpoint": "http://%%host%%:9400/metrics", "tags":["model:openai/gpt-oss-120b","deployment:gpt-oss-single","ip:${HOST_IP}"]}]'
      com.datadoghq.ad.logs: '[{"source": "dcgm-exporter", "service": "dcgm-exporter", "tags":["model:openai/gpt-oss-120b","deployment:gpt-oss-single","ip:${HOST_IP}"]}]'

volumes:
  hugginface_cache:
  vllm_cache:
