#!/usr/bin/env python3
# How to run: python3 scripts/kvq/prepare_glm53_kvshare_ab.py --write   (or --check)
"""Generate prod/GLM-5.3-Flash-SGL-TP2x4-W4AFP8-KVShare-AB.yaml: an in-host A/B of the shared KV
host tier on one base-tier host, from the live base file prod/GLM-5.3-Flash-SGL-TP2x4-W4AFP8.yaml.

Control: r1 (GPUs 0-1) and r2 (GPUs 2-3), byte-identical to the base file.
Treatment: r3 (GPUs 4-5) and r4 (GPUs 6-7) share an L3 HiCache file tier on a tmpfs volume only
they mount (`kvshare`). The engine image is unchanged (v6); the shared-tier change is applied at
start by scripts/kvq/glm53_shared_kv_startup_patch.py (cvm-compose-files PR #304 ported to v6,
hash-checked before and after, fail closed: a mismatch stops the replica instead of serving
unpatched).

RAM is held equal between the arms: each control replica keeps its 325 GiB L2; each treatment
replica gets 250 GiB L2 plus half of a 150 GiB shared L3 store (2 x 250 + 150 = 650 GiB = 2 x 325).
The proxy, its conversation affinity and every other service are unchanged, so both arms see the
same routing. Everything the A/B reads is already exported or added by the patch:
  sglang:ghost_* (pooled prize, other-replica-only tokens per replica), sglang:kv_tier_*,
  sglang:storage_prefetch_hit_tokens_total, and sglang:kvshare_storage_hit_tokens_total{source}
  / sglang:kvshare_storage_written_tokens_total (self vs peer attribution, this patch).
Runbook: docs/glm53-kvshare-ab.md. Rollback: deploy the base file at the current tag with the
same scoped service list (r3, r4); the base file defines no `kvshare` volume, so the tmpfs store
goes with it.
"""
import argparse, difflib, hashlib, re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = Path("prod/GLM-5.3-Flash-SGL-TP2x4-W4AFP8.yaml")
TARGET = Path("prod/GLM-5.3-Flash-SGL-TP2x4-W4AFP8-KVShare-AB.yaml")
# Host-level variant: all four replicas share one store; another base-tier host is the control.
TARGET4 = Path("prod/GLM-5.3-Flash-SGL-TP2x4-W4AFP8-KVShare4.yaml")
PATCH = Path("scripts/kvq/glm53_shared_kv_startup_patch.py")
TREATMENT = ("r3", "r4")
VARIANT_SUFFIX = "-kvshare-l3file-v1"
SHARED_ARGS = ("--hicache-host-memory-mode cache --hicache-storage-backend file "
               "--hicache-storage-prefetch-policy wait_complete")


def one(text, old, new, label):
    n = text.count(old)
    if n != 1:
        sys.exit(f"{label}: expected 1 anchor in {SOURCE}, found {n} (base file changed; update the generator)")
    return text.replace(old, new)


def block(text, indent):
    pad = " " * indent
    return "\n".join((pad + l) if l.strip() else "" for l in text.replace("$", "$$").rstrip("\n").split("\n"))


def render(four=False):
    treatment = ("r1", "r2", "r3", "r4") if four else TREATMENT
    suffix = "-kvshare4-l3file-v1" if four else VARIANT_SUFFIX
    vol = "kvshare4" if four else "kvshare"
    store, tmpfs = ("300GiB", "320g") if four else ("150GiB", "160g")
    src = (ROOT / SOURCE).read_text()
    patch = (ROOT / PATCH).read_text()
    out = src

    # 1) Header.
    if four:
        out = ("# GENERATED by scripts/kvq/prepare_glm53_kvshare_ab.py --four from " + str(SOURCE) + " -- do not edit by hand.\n"
               "# HOST-LEVEL A/B TREATMENT: all four replicas share an L3 HiCache file tier on the `kvshare4` tmpfs\n"
               "# volume (startup patch glm53_shared_kv_startup_patch, RAM-neutral 4 x 250 + 300 GiB = 4 x 325 GiB).\n"
               "# The control is another base-tier host on the base file. Runbook: docs/glm53-kvshare-ab.md.\n"
               "# Roll one replica at a time with scoped compose/up (scripts/kvq/deploy_kvshare_ab.py --four).\n") + out
    else:
        out = ("# GENERATED by scripts/kvq/prepare_glm53_kvshare_ab.py from " + str(SOURCE) + " -- do not edit by hand.\n"
               "# IN-HOST A/B: r1+r2 = control (unchanged), r3+r4 = treatment sharing an L3 HiCache file tier on\n"
               "# the `kvshare` tmpfs volume (startup patch glm53_shared_kv_startup_patch, RAM-neutral 250+250+150 GiB).\n"
               "# Runbook: docs/glm53-kvshare-ab.md. Deploy only r3/r4 (+ nothing else) with a scoped compose/up.\n") + out

    # 2) Treatment anchor: the candidate argv, launched through the startup patch, plus the file tier.
    cand_start = out.index("x-sg-glm53-flash-candidate: &sg-glm53-flash-candidate\n")
    cmd_start = out.index("  command: >\n      sglang serve\n", cand_start)
    cmd_end = out.index("\n\n", cmd_start)
    argv = " ".join(l.strip() for l in out[cmd_start:cmd_end].splitlines()[1:])  # "sglang serve --model-path ..."
    assert argv.startswith("sglang serve --model-path"), argv[:80]
    anchor = f"""x-sg-glm53-flash-kvshare: &sg-glm53-flash-kvshare
  # Treatment arm of the in-host shared-KV A/B: the candidate argv above, started through the
  # shared-KV startup patch (exact-anchor edits of the v6 image's mem_cache files, verified by
  # sha256 before and after; any mismatch exits before serving), plus an L3 HiCache file tier on
  # the `kvshare` tmpfs volume that both treatment replicas mount.
  <<: *sg-glm53-flash-candidate
  entrypoint: ["bash", "-c"]
  command:
    - |
      python3 /etc/glm53/shared_kv_patch.py || exit 1
      exec {argv} {SHARED_ARGS}
  configs:
    - source: glm53_shared_kv_patch
      target: /etc/glm53/shared_kv_patch.py
      mode: 0444
  volumes:
    - kernel_cache:/root/.cache
    - huggingface_cache:/root/.cache/huggingface
    - ghost:/ghost
    - {vol}:/kvshared

"""
    out = out[:cmd_end + 2] + anchor + out[cmd_end + 2:]

    # 3) Treatment replicas: anchor, L2 budget, file-tier env, variant label.
    n = len(treatment)
    if four:
        budget_note = "250 GiB L2 + 1/4 of the 300 GiB shared L3 store = the base file's 325 GiB"
        share_head = ("# Shared L3 tier (all four replicas). The store is the `kvshare4` tmpfs every replica\n"
                      "# mounts; each replica's evictor is capped at MAX_SIZE (non-owner TP ranks at 0.25x\n"
                      "# for their own mamba shards), and 4 x 1.25 x 60Gi = 300Gi = the store budget.")
        vol_note = "300 GiB"
    else:  # byte-identical to the deployed 2-way file
        budget_note = "250 GiB L2 + half of the 150 GiB shared L3 store = the control's 325 GiB"
        share_head = ("# Shared L3 tier (treatment only). The store is the `kvshare` tmpfs both treatment\n"
                      "# replicas mount; each replica's evictor is capped at MAX_SIZE (non-owner TP ranks at\n"
                      "# 0.25x for their own mamba shards), and 2 x 1.25 x 60Gi = 150Gi = the store budget.")
        vol_note = "150 GiB"

    def tier_env(pad, r):
        lines = [share_head,
                 "SGLANG_HICACHE_FILE_BACKEND_STORAGE_DIR=/kvshared",
                 "# Positive-lookup cache (5 s TTL; misses fall back to a stat, so pages a peer",
                 "# just wrote are found). Without it every existence check scans the whole store.",
                 "SGLANG_HICACHE_FILE_BACKEND_ENABLE_METADATA_CACHE=1",
                 "SGLANG_HICACHE_FILE_BACKEND_MAX_SIZE=${GLM53_KVSHARE_FILE_MAX:-60Gi}",
                 f"SGLANG_HICACHE_SHARED_STORE_BUDGET=${{GLM53_KVSHARE_STORE_BUDGET:-{store}}}",
                 "# sglang:kvshare_storage_* self/peer attribution (TP rank 0).",
                 "SGLANG_KVSHARE_METRICS=1"]
        if four:
            # One INFO line per storage restore (pages, MB, seconds, MB/s): the prod measure of
            # restore cost against the gpu13 qualification (13.3-14.2 s at ~220K tokens).
            lines += ["# One INFO line per storage restore (pages, MB, s, MB/s), to compare prod restore",
                      "# cost with the gpu13 qualification (13.3-14.2 s at ~220K tokens).",
                      "SGLANG_KVSHARE_LOG_READS=1"]
        res = ""
        for l in lines:
            for sub in l.split("\n"):
                res += pad + (sub if sub.startswith("#") else "- " + sub) + "\n"
        return res

    for r in treatment:
        svc = f"  model-sg-glm53-w4afp8-tp2-{r}:\n    <<: *sg-glm53-flash-candidate\n"
        out = one(out, svc, svc.replace("*sg-glm53-flash-candidate", "*sg-glm53-flash-kvshare"), f"{r} anchor")
        s0 = out.index(f"  model-sg-glm53-w4afp8-tp2-{r}:\n")
        s1 = out.index("\n  # ---", s0) if "\n  # ---" in out[s0:] else len(out)
        body = out[s0:s1]
        if r != "r1":
            body = one(body, "      - SGLANG_HICACHE_RAM_BUDGET=${GLM53_HICACHE_RAM_BUDGET:-325GiB}\n",
                       f"      # Treatment: {budget_note}.\n"
                       "      - SGLANG_HICACHE_RAM_BUDGET=${GLM53_KVSHARE_RAM_BUDGET:-250GiB}\n", f"{r} ram budget")
            body = one(body, f"      - SGLANG_GHOST_CACHE_REPLICA={r}\n      - SGLANG_KV_TIER_METRICS=1\n",
                       f"      - SGLANG_GHOST_CACHE_REPLICA={r}\n      - SGLANG_KV_TIER_METRICS=1\n" + tier_env("      ", r),
                       f"{r} file tier env")
        body = body.replace("-strict-budget8192-obs-v1", "-strict-budget8192-obs-v1" + suffix)
        assert body.count(suffix) == 2, f"{r}: expected 2 config_variant labels"
        out = out[:s0] + body + out[s1:]
    if "r1" in treatment:
        # r1 has no environment of its own: it inherits the common anchor's list, which is
        # written for r1 (SGLANG_GHOST_CACHE_REPLICA=r1). Every service on that anchor is a GLM
        # replica, and in this file all of them override it except r1, so edit it in place.
        out = one(out, "    - SGLANG_HICACHE_RAM_BUDGET=${GLM53_HICACHE_RAM_BUDGET:-325GiB}\n",
                  f"    # Treatment (r1 inherits this list): {budget_note}.\n"
                  "    - SGLANG_HICACHE_RAM_BUDGET=${GLM53_KVSHARE_RAM_BUDGET:-250GiB}\n", "r1 ram budget")
        out = one(out, "    - SGLANG_GHOST_CACHE_REPLICA=r1\n    - SGLANG_KV_TIER_METRICS=1\n",
                  "    - SGLANG_GHOST_CACHE_REPLICA=r1\n    - SGLANG_KV_TIER_METRICS=1\n" + tier_env("    ", "r1"),
                  "r1 file tier env")

    # 4) The shared store volume (in-memory; gone when the treatment is rolled back).
    out = one(out, "  ghost:\n    driver: local\n    driver_opts:\n      type: tmpfs\n      device: tmpfs\n      o: \"size=1m,mode=0700\"\n",
              "  ghost:\n    driver: local\n    driver_opts:\n      type: tmpfs\n      device: tmpfs\n      o: \"size=1m,mode=0700\"\n"
              f"  # Shared L3 HiCache store for the treatment replicas only. Sized above the {vol_note} store\n"
              "  # budget so the evictors, not tmpfs, bound it.\n"
              f"  {vol}:\n    driver: local\n    driver_opts:\n      type: tmpfs\n      device: tmpfs\n"
              f"      o: \"size=${{GLM53_KVSHARE_TMPFS:-{tmpfs}}},mode=0700\"\n", "kvshare volume")

    # 5) The startup patch as a config.
    out = one(out, "\nconfigs:\n", "\nconfigs:\n  glm53_shared_kv_patch:\n    content: |\n" + block(patch, 6) + "\n\n", "configs block")
    return out


HICACHE_FLAGS = ("--enable-hierarchical-cache", "--hicache-write-policy", "--hicache-io-backend", "--hicache-mem-layout")
OFF_SUFFIX = "-hicacheoff-v1"


def target_off(replicas):
    return Path(f"prod/GLM-5.3-Flash-SGL-TP2x4-W4AFP8-HiCacheOff-{''.join(r[1] for r in replicas)}.yaml")


def render_hicache_off(replicas):
    """Arm B of the 2026-10-08 online test: `replicas` run the base candidate argv without HiCache
    (no host L2); the other replicas are byte-identical to the base file. HiCache env vars are
    left in place: without --enable-hierarchical-cache nothing reads them."""
    src = (ROOT / SOURCE).read_text()
    out = ("# GENERATED by scripts/kvq/prepare_glm53_kvshare_ab.py --hicache-off " + ",".join(replicas) + " from "
           + str(SOURCE) + " -- do not edit by hand.\n"
           "# ONLINE TEST ARM B: " + " + ".join(replicas) + " run without HiCache (no host L2 tier); the other replicas\n"
           "# are the unchanged control (arm A). Plan: tee-bench exp 31. Deploy only those replicas, scoped.\n") + src
    cand_start = out.index("x-sg-glm53-flash-candidate: &sg-glm53-flash-candidate\n")
    cmd_start = out.index("  command: >\n      sglang serve\n", cand_start)
    cmd_end = out.index("\n\n", cmd_start)
    cmd = out[cmd_start:cmd_end]
    kept = [l for l in cmd.split("\n") if not l.strip().startswith(HICACHE_FLAGS)]
    removed = len(cmd.split("\n")) - len(kept)
    assert removed == len(HICACHE_FLAGS), f"expected {len(HICACHE_FLAGS)} HiCache flags in the candidate argv, removed {removed}"
    anchor = ("x-sg-glm53-flash-nohicache: &sg-glm53-flash-nohicache\n"
              "  # Arm B: the candidate argv above without HiCache (" + ", ".join(HICACHE_FLAGS) + ").\n"
              "  # Everything else, including the mamba slots and the environment, is the candidate's.\n"
              "  <<: *sg-glm53-flash-candidate\n" + "\n".join(kept) + "\n\n")
    out = out[:cmd_end + 2] + anchor + out[cmd_end + 2:]
    for r in replicas:
        svc = f"  model-sg-glm53-w4afp8-tp2-{r}:\n    <<: *sg-glm53-flash-candidate\n"
        out = one(out, svc, svc.replace("*sg-glm53-flash-candidate", "*sg-glm53-flash-nohicache"), f"{r} anchor")
        s0 = out.index(f"  model-sg-glm53-w4afp8-tp2-{r}:\n")
        s1 = out.index("\n  # ---", s0) if "\n  # ---" in out[s0:] else len(out)
        body = out[s0:s1].replace("-strict-budget8192-obs-v1", "-strict-budget8192-obs-v1" + OFF_SUFFIX)
        assert body.count(OFF_SUFFIX) == 2, f"{r}: expected 2 config_variant labels"
        out = out[:s0] + body + out[s1:]
    return out



SOURCE13 = Path("prod/small-models.yaml")
TARGET13 = Path("prod/small-models-GLM53-KVShare2.yaml")
D_SUFFIX = "-kvshare2-l3file-v1"


def render_gpu13(pool=False):
    """Arm D of the 2026-10-08 online test: gpu13's two long-context GLM replicas (r1a GPUs 4-5,
    r1b GPUs 6-7) share one L3 HiCache file store on the `kvshare2` tmpfs. RAM-neutral:
    2 x 250 GiB L2 + 150 GiB store = 2 x 325 GiB. Every other service in small-models.yaml is
    byte-identical; deploy only r1a/r1b with a scoped compose/up."""
    src = (ROOT / SOURCE13).read_text()
    patch = (ROOT / PATCH).read_text()
    l2, store, cap, tmpfs = ("64GiB", "520GiB", "208Gi", "540g") if pool else ("250GiB", "150GiB", "60Gi", "160g")
    suffix = "-kvsharepool-v1" if pool else D_SUFFIX
    budget_note = ("64 GiB private L2 (staging) + half of the 520 GiB shared L3 store = 325 GiB" if pool
                   else "250 GiB L2 + half of the 150 GiB shared L3 store = 325 GiB")
    out = ("# GENERATED by scripts/kvq/prepare_glm53_kvshare_ab.py --gpu13 from " + str(SOURCE13) + " -- do not edit by hand.\n"
           + (("# ONLINE TEST ARM D' (exp 32): model-sg-glm53-w4afp8-tp2-r1a + r1b pool their host cache: 64 GiB private L2\n"
            "# each (staging) + one 520 GiB shared L3 store on `kvshare2` = 2 x 325 GiB (startup patch glm53_shared_kv).\n") if pool else
           ("# ONLINE TEST ARM D: model-sg-glm53-w4afp8-tp2-r1a + r1b share an L3 HiCache file tier on the `kvshare2`\n"
           "# tmpfs volume (startup patch glm53_shared_kv_startup_patch, 2 x 250 GiB L2 + 150 GiB store = 2 x 325 GiB).\n"))
           + "# Every other service is unchanged. Plan: tee-bench exp 31. Deploy only r1a/r1b, one at a time, scoped.\n") + src

    def argv_of(block_start, indent):
        start = out.index(" " * indent + "command: >\n", block_start)
        lines = out[start:].split("\n")[1:]
        argv = []
        for l in lines:
            if not l.startswith(" " * (indent + 2)) or not l.strip():
                break
            argv.append(l.strip())
        assert argv[0] == "sglang serve" and "--enable-hierarchical-cache" in argv, argv[:3]
        end = start + len(" " * indent + "command: >\n") + sum(len(l) + 1 for l in lines[:len(argv)])
        return " ".join(argv), start, end

    def kv_block(argv, pad):
        p = " " * pad
        return (f"{p}# Arm D: launched through the shared-KV startup patch (fail closed), plus the L3 file tier\n"
                f"{p}# on the `kvshare2` tmpfs both GLM replicas mount.\n"
                f"{p}entrypoint: [\"bash\", \"-c\"]\n"
                f"{p}command:\n{p}  - |\n{p}    python3 /etc/glm53/shared_kv_patch.py || exit 1\n"
                f"{p}    exec {argv} {SHARED_ARGS}\n"
                f"{p}configs:\n{p}  - source: glm53_shared_kv_patch\n{p}    target: /etc/glm53/shared_kv_patch.py\n{p}    mode: 0444\n"
                f"{p}volumes:\n{p}  - kernel_cache:/root/.cache\n{p}  - hugginface_cache:/root/.cache/huggingface\n"
                f"{p}  - ghost:/ghost\n{p}  - kvshare2:/kvshared\n")

    def tier_env(pad):
        p = " " * pad
        return "".join(p + l + "\n" for l in [
            "# Shared L3 tier (arm D). The store is the `kvshare2` tmpfs both GLM replicas mount; each",
            "# replica's evictor is capped at MAX_SIZE (non-owner TP ranks at 0.25x for their own mamba",
            ("# shards), and 2 x 1.25 x 208Gi = 520Gi = the store budget." if pool else "# shards), and 2 x 1.25 x 60Gi = 150Gi = the store budget."),
            "- SGLANG_HICACHE_FILE_BACKEND_STORAGE_DIR=/kvshared",
            "- SGLANG_HICACHE_FILE_BACKEND_ENABLE_METADATA_CACHE=1",
            f"- SGLANG_HICACHE_FILE_BACKEND_MAX_SIZE=${{GLM53_KVSHARE_FILE_MAX:-{cap}}}",
            f"- SGLANG_HICACHE_SHARED_STORE_BUDGET=${{GLM53_KVSHARE_STORE_BUDGET:-{store}}}",
            "- SGLANG_KVSHARE_METRICS=1",
            "# One INFO line per storage restore (pages, MB, s, MB/s).",
            "- SGLANG_KVSHARE_LOG_READS=1"])

    # r1b first (its own command and environment), then r1a (anchor argv; body gets the block).
    b0 = out.index("  model-sg-glm53-w4afp8-tp2-r1b:\n")
    assert "\n    configs:" not in out[b0:out.index("\n  glm53-ghost-aggregator:", b0)]
    argv_b, cs, ce = argv_of(b0, 4)
    out = out[:cs] + kv_block(argv_b, 4) + out[ce:]
    out = one(out, "      - SGLANG_HICACHE_RAM_BUDGET=${GLM53_R1B_HICACHE_RAM_BUDGET:-325GiB}\n",
              f"      # Arm D: {budget_note}.\n"
              f"      - SGLANG_HICACHE_RAM_BUDGET=${{GLM53_KVSHARE_RAM_BUDGET:-{l2}}}\n", "r1b ram budget")
    out = one(out, "      - SGLANG_GHOST_CACHE_REPLICA=r1b\n      - SGLANG_KV_TIER_METRICS=1\n",
              "      - SGLANG_GHOST_CACHE_REPLICA=r1b\n      - SGLANG_KV_TIER_METRICS=1\n" + tier_env(6), "r1b tier env")
    a_anchor = out.index("x-sg-glm53-flash-common: &sg-glm53-flash-common\n")
    argv_a, _, _ = argv_of(a_anchor, 2)
    a0 = out.index("  model-sg-glm53-w4afp8-tp2-r1a:\n")
    cn = "    container_name: model-sg-glm53-w4afp8-tp2-r1a\n"
    i = out.index(cn, a0) + len(cn)
    out = out[:i] + kv_block(argv_a, 4) + out[i:]
    # r1a has no environment of its own: it inherits the GLM anchor's (written for r1a); r1b
    # overrides it, and no other service uses that anchor.
    assert out.count("<<: *sg-glm53-flash-common") == 2
    out = one(out, "    - SGLANG_HICACHE_RAM_BUDGET=${GLM53_R1A_HICACHE_RAM_BUDGET:-325GiB}\n",
              f"    # Arm D (r1a inherits this list): {budget_note}.\n"
              f"    - SGLANG_HICACHE_RAM_BUDGET=${{GLM53_KVSHARE_RAM_BUDGET:-{l2}}}\n", "r1a ram budget")
    out = one(out, "    - SGLANG_GHOST_CACHE_REPLICA=r1a\n    - SGLANG_KV_TIER_METRICS=1\n",
              "    - SGLANG_GHOST_CACHE_REPLICA=r1a\n    - SGLANG_KV_TIER_METRICS=1\n" + tier_env(4), "r1a tier env")
    for r in ("r1a", "r1b"):
        s0 = out.index(f"  model-sg-glm53-w4afp8-tp2-{r}:\n")
        s1 = out.index("\n  model-sg-glm53-w4afp8-tp2-r1b:", s0) if r == "r1a" else out.index("\n  glm53-ghost-aggregator:", s0)
        body = out[s0:s1]
        body, n1 = re.subn(r'("config_variant:[^",]+)"', lambda m: m.group(1) + suffix + '"', body)
        body, n2 = re.subn(r'(nearai\.otel\.config_variant: "[^"]+)"', lambda m: m.group(1) + suffix + '"', body)
        assert (n1, n2) == (1, 1), (r, n1, n2)
        out = out[:s0] + body + out[s1:]
    out = one(out, '  ghost:\n    driver: local\n    driver_opts:\n      type: tmpfs\n      device: tmpfs\n      o: "size=1m,mode=0700"\n',
              '  ghost:\n    driver: local\n    driver_opts:\n      type: tmpfs\n      device: tmpfs\n      o: "size=1m,mode=0700"\n'
              f"  # Shared L3 HiCache store for the two GLM replicas only (arm D). Sized above the {store.replace('GiB', ' GiB')}\n"
              "  # store budget so the evictors, not tmpfs, bound it.\n"
              "  kvshare2:\n    driver: local\n    driver_opts:\n      type: tmpfs\n      device: tmpfs\n"
              f'      o: "size=${{GLM53_KVSHARE_TMPFS:-{tmpfs}}},mode=0700"\n', "kvshare2 volume")
    out = one(out, "\nconfigs:\n", "\nconfigs:\n  glm53_shared_kv_patch:\n    content: |\n" + block(patch, 6) + "\n\n", "configs block")
    return out



V7_SOURCE = Path("prod/GLM-5.3-Flash-SGL-TP2x4-W4AFP8-V7Canary.yaml")
V7_OFF_SUFFIX = "-hicacheoff-v1"


def service_block(text, name):
    """(start, end) of a top-level compose service: from its key line to the next line at
    service indent (another service, or the comment that precedes one)."""
    a = text.index(f"  {name}:\n")
    m = re.compile(r"\n  \S").search(text, a + 1)
    return a, (m.start() + 1 if m else len(text))


# Per-replica identity fields: (regex with one group, kind). Their values in the clone are taken
# from the target's own original block, so the clone keeps the target's GPUs, ports and labels.
IDENTITY_FIELDS = [
    r'\n    container_name: (\S+)\n',
    r'--dist-init-addr (\S+)',
    r'- (SGLANG_HICACHE_RAM_BUDGET=\S+)\n',
    r'SGLANG_GHOST_CACHE_REPLICA=(\S+)\n',
    r'device_ids: (\[[^\]]*\])',
    r'nearai\.otel\.container_name: "([^"]+)"',
    r'nearai\.otel\.instance: "([^"]+)"',
    r'nearai\.otel\.gpu_pair: "([^"]+)"',
    r'"(instance:[^"]+)"',
    r'"(gpu_pair:[^"]+)"',
]


def render_v7_hicache_off(target="r3", source_replica="r4", source=V7_SOURCE, header_arm="B'"):
    """`target` becomes a copy of the v7 canary replica (`source_replica`) in `source` without
    HiCache, so target vs source isolates HiCache off on top of v7. Identity fields stay the
    target's own (IDENTITY_FIELDS); the collector's scrape labels for the target describe v7."""
    src = (ROOT / source).read_text()
    svc_t, svc_s = f"model-sg-glm53-w4afp8-tp2-{target}", f"model-sg-glm53-w4afp8-tp2-{source_replica}"
    s0, s1 = service_block(src, svc_s)
    blk = src[s0:s1]
    t0, t1 = service_block(src, svc_t)
    tblk = src[t0:t1]
    assert "fa730e6e62b2" in blk, "source replica is not the v7 canary"
    lines = blk.split("\n")
    kept = [l for l in lines if not l.strip().startswith(HICACHE_FLAGS)]
    assert len(lines) - len(kept) == len(HICACHE_FLAGS), "expected the 4 HiCache flags in the v7 argv"
    blk = "\n".join(kept)
    blk = blk.replace(f"  {svc_s}:\n", f"  {svc_t}:\n", 1)
    for pat in IDENTITY_FIELDS:
        # Replace the WHOLE matched text (e.g. `nearai.otel.instance: "4"`), never the bare value:
        # replacing a value like "4" would rewrite every 4 in the block (W4AFP8, fp8_e4m3, ...).
        ms, mt = list(re.finditer(pat, blk)), list(re.finditer(pat, tblk))
        if not mt:
            # The target inherits this field from an anchor (same value on every replica of that
            # file, e.g. the base tier's dist-init port in separate network namespaces): keep it.
            assert len(ms) <= 1, (pat, [m.group(0) for m in ms])
            continue
        assert len(ms) == len(mt) == 1, (pat, [m.group(0) for m in ms], [m.group(0) for m in mt])
        assert blk.count(ms[0].group(0)) == 1, (pat, ms[0].group(0))
        blk = blk.replace(ms[0].group(0), mt[0].group(0))
    blk, nv = re.subn(r'("config_variant:[^",]+)"', lambda m: m.group(1) + V7_OFF_SUFFIX + '"', blk)
    blk, nv2 = re.subn(r'(nearai\.otel\.config_variant: "[^"]+)"', lambda m: m.group(1) + V7_OFF_SUFFIX + '"', blk)
    assert (nv, nv2) == (1, 1), (nv, nv2)
    assert svc_s not in blk and f"REPLICA={source_replica}\n" not in blk
    out = src[:t0] + blk + src[t1:]
    # The collector's static scrape labels for the target must describe the v7 engine too
    # (precision, engine image, variant), or the OTel label contract check fails and Prometheus
    # would mislabel the arm.
    def job(text, svc):
        j0 = text.index(f"- job_name: sglang-{svc}\n")
        j1 = text.index("- job_name:", j0 + 10)
        return j0, j1
    s4 = out[slice(*job(out, svc_s))]
    lab = {k: re.search(rf'\n\s+{k}: "([^"]+)"', s4).group(1) for k in ("precision", "config_variant", "engine_image")}
    j0, j1 = job(out, svc_t)
    jt = out[j0:j1]
    for k, v in lab.items():
        if k == "config_variant":
            v = v + V7_OFF_SUFFIX
        jt, n = re.subn(rf'(\n\s+{k}: ")[^"]+(")', lambda m: m.group(1) + v + m.group(2), jt)
        assert n == 1, (k, n)
    out = out[:j0] + jt + out[j1:]
    hdr = ("# GENERATED by scripts/kvq/prepare_glm53_kvshare_ab.py --v7-hicache-off " + target + " from " + str(source)
           + " -- do not edit by hand.\n# ONLINE TEST ARM " + header_arm + " (tee-bench exp 32): " + target + " = the v7 canary replica ("
           + source_replica + ") without HiCache\n# (no host L2). Everything else is byte-identical to the canary file.\n")
    return hdr + out


PEERKV_TARGET = Path("prod/GLM-5.3-Flash-SGL-TP2x4-W4AFP8-V7-HiCacheOff-PeerKV.yaml")
PEERKV_PATCH = Path("scripts/kvq/peerkv/glm53_peerkv_startup_patch.py")
PEERKV_ENGINE = Path("scripts/kvq/peerkv/peerkv_engine.py")
PEERKV_PAIR = ("r1", "r2")
# Appended to prod's config_variant: treatment = peerkv (+ expandable_segments:False), control = only
# expandable_segments:False, so peerkv is the only arm difference.
PEERKV_SUFFIX, EXPFALSE_SUFFIX = "-peerkv-v1", "-expfalse-v1"
# Each replica's own GPUs on the base file (the 4 TP2 islands of gpu04).
PEERKV_GPUS = {"r1": '["0","1"]', "r2": '["2","3"]', "r3": '["4","5"]', "r4": '["6","7"]'}


def cfg(name, text):
    """Content-addressed config name: compose reuses a config whose name is unchanged, so a changed
    engine or patch gets a new name (and the replica is recreated) instead of a stale mount."""
    return f"{name}_{hashlib.sha256(text.encode()).hexdigest()[:8]}"


def render_peerkv():
    """gpu04 A/B on the current base file (v7 fleet config: v7 + FP8 KV + mr64 + HiCache off). The
    engine argv is prod's on every replica. All four replicas get expandable_segments:False (legacy
    cudaIpc cannot export VMM memory); r1+r2 additionally run GPU-to-GPU peer prefix fetch (peerkv:
    startup patch + engine, both see GPUs 0-3 in PCI order, host IPC/PID namespaces, a shared tmpfs
    for the IPC handle files). r3+r4 are the control."""
    base = (ROOT / SOURCE).read_text()
    patch, engine = (ROOT / PEERKV_PATCH).read_text(), (ROOT / PEERKV_ENGINE).read_text()
    c_patch, c_engine = cfg("glm53_peerkv_patch_py", patch), cfg("glm53_peerkv_engine_py", engine)
    out = base
    # Prod's argv: the candidate anchor's folded `command: >` (no service overrides it). Folding joins
    # the lines with single spaces, so the exec'd string is exactly what compose passes today.
    a0 = out.index("x-sg-glm53-flash-candidate: &sg-glm53-flash-candidate\n")
    c0 = out.index("  command: >\n      sglang serve\n", a0)
    c1 = out.index("\n\n", c0)
    argv = " ".join(l.strip() for l in out[c0:c1].split("\n")[1:])
    assert argv.startswith("sglang serve --model-path") and "$" not in argv and "--base-gpu-id" not in argv, argv[:80]
    assert "--enable-hierarchical-cache" not in argv and "fp8_e4m3" in argv, "base file is not the v7 HiCache-off fleet config"
    assert out.count("<<: *sg-glm53-flash-candidate\n") == 4 and out.count("<<: *sg-glm53-flash-common\n") == 1
    variant = re.search(r'nearai\.otel\.config_variant: "([^"]+)"', out[out.index("  model-sg-glm53-w4afp8-tp2-r1:\n"):]).group(1)
    assert variant.endswith("-v7"), variant
    alloc_note = ("# A/B (both arms): False, so peerkv is the only arm difference. Expandable segments put\n"
                  "# allocations in CUDA VMM memory, which legacy cudaIpc (peerkv) cannot export.\n")

    def peer_env(pad, r, name, sib):
        return "".join(pad + l + "\n" for l in [
            "# peerkv (treatment): fetch a long cached prefix from the sibling's VRAM over CUDA IPC",
            "# instead of re-prefilling it. GLM53_PEERKV=0 is the kill switch (no patch, inert).",
            "- CUDA_DEVICE_ORDER=PCI_BUS_ID",
            "- SGLANG_PEERKV=${GLM53_PEERKV:-1}",
            f"- SGLANG_PEERKV_SELF={name}",
            f"- SGLANG_PEERKV_PEER={sib}",
            "- SGLANG_PEERKV_DIR=/peerkv",
            "- SGLANG_PEERKV_MIN_TOKENS=${GLM53_PEERKV_MIN_TOKENS:-16384}"])

    for r in ("r1", "r2", "r3", "r4"):
        name = f"model-sg-glm53-w4afp8-tp2-{r}"
        peer = r in PEERKV_PAIR
        sib = f"model-sg-glm53-w4afp8-tp2-{PEERKV_PAIR[1 - PEERKV_PAIR.index(r)]}" if peer else None
        t0, t1 = service_block(out, name)
        blk = out[t0:t1]
        assert "    command:" not in blk and "    entrypoint:" not in blk, f"{r} overrides the anchor's command"
        if r == "r1":
            # r1 has no environment of its own: it inherits the common anchor's list (written for r1;
            # every other user of the anchor, r2-r4, overrides it), so edit that list in place.
            assert "    environment:" not in blk
            out = one(out, "\n    - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True\n",
                      "\n" + "".join("    " + l + "\n" for l in alloc_note.splitlines()) +
                      "    - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:False\n", "r1 alloc conf")
            out = one(out, "\n    - SGLANG_GHOST_CACHE_REPLICA=r1\n    - SGLANG_KV_TIER_METRICS=1\n",
                      "\n    - SGLANG_GHOST_CACHE_REPLICA=r1\n    - SGLANG_KV_TIER_METRICS=1\n" + peer_env("    ", r, name, sib),
                      "r1 peerkv env")
            t0, t1 = service_block(out, name)
            blk = out[t0:t1]
        else:
            blk = one(blk, "      - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True\n",
                      "".join("      " + l + "\n" for l in alloc_note.splitlines()) +
                      "      - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:False\n", f"{r} alloc conf")
            if peer:
                blk = one(blk, f"      - SGLANG_GHOST_CACHE_REPLICA={r}\n      - SGLANG_KV_TIER_METRICS=1\n",
                          f"      - SGLANG_GHOST_CACHE_REPLICA={r}\n      - SGLANG_KV_TIER_METRICS=1\n" + peer_env("      ", r, name, sib),
                          f"{r} peerkv env")
        suffix = PEERKV_SUFFIX if peer else EXPFALSE_SUFFIX
        if peer:
            gpu = 2 * (int(r[1]) - 1)
            blk = one(blk, f"              device_ids: {PEERKV_GPUS[r]}\n",
                      '              # peerkv: both treatment replicas see GPUs 0-3 in the same (PCI) order, so a\n'
                      '              # peer pool is addressable over CUDA IPC; --base-gpu-id picks the own pair.\n'
                      '              device_ids: ["0","1","2","3"]\n', f"{r} gpus")
            cn = f"    container_name: {name}\n"
            blk = one(blk, cn, cn + (
                "    # peerkv startup patch (fail closed: a mismatch exits before serving), then prod's argv\n"
                "    # (the candidate anchor's) plus --base-gpu-id for the own pair among the four visible GPUs.\n"
                "    entrypoint: [\"bash\", \"-c\"]\n"
                "    command:\n"
                "      - |\n"
                "        if [ \"$${SGLANG_PEERKV:-0}\" = \"1\" ]; then python3 /etc/glm53/glm53_peerkv_startup_patch.py || exit 1; fi\n"
                f"        exec {argv} --base-gpu-id {gpu}\n"
                "    # CUDA IPC across containers needs the host IPC and PID namespaces.\n"
                "    ipc: host\n"
                "    pid: host\n"
                "    configs:\n"
                f"      - source: {c_patch}\n        target: /etc/glm53/glm53_peerkv_startup_patch.py\n        mode: 0444\n"
                f"      - source: {c_engine}\n        target: /etc/glm53/peerkv_engine.py\n        mode: 0444\n"
                "    volumes:\n"
                "      - kernel_cache:/root/.cache\n"
                "      - huggingface_cache:/root/.cache/huggingface\n"
                "      - ghost:/ghost\n"
                "      - peerkv:/peerkv\n"), f"{r} command")
        else:
            assert f"device_ids: {PEERKV_GPUS[r]}" in blk, r
        blk, nv = re.subn(r'("config_variant:[^",]+)"', lambda m: m.group(1) + suffix + '"', blk)
        blk, nv2 = re.subn(r'(nearai\.otel\.config_variant: "[^"]+)"', lambda m: m.group(1) + suffix + '"', blk)
        assert (nv, nv2) == (1, 1), (r, nv, nv2)
        out = out[:t0] + blk + out[t1:]
        # Collector scrape labels for this replica carry the same variant (OTel label contract).
        j0 = out.index(f"- job_name: sglang-{name}\n")
        j1 = out.index("- job_name:", j0 + 10)
        jt, n = re.subn(r'(\n\s+config_variant: ")[^"]+(")', lambda m: m.group(1) + variant + suffix + m.group(2), out[j0:j1])
        assert n == 1, (r, n)
        out = out[:j0] + jt + out[j1:]
    assert "SGLANG_PEERKV_HOTRELOAD" not in out
    ghost_vol = '  ghost:\n    driver: local\n    driver_opts:\n      type: tmpfs\n      device: tmpfs\n      o: "size=1m,mode=0700"\n'
    out = one(out, ghost_vol, ghost_vol +
              "  # peerkv (r1+r2 only): per-rank CUDA IPC handle files and the lend sockets (tiny).\n"
              '  peerkv:\n    driver: local\n    driver_opts:\n      type: tmpfs\n      device: tmpfs\n      o: "size=64m,mode=0700"\n',
              "peerkv volume")
    out = one(out, "\nconfigs:\n", f"\nconfigs:\n  {c_patch}:\n    content: |\n" + block(patch, 6) + "\n\n"
              f"  {c_engine}:\n    content: |\n" + block(engine, 6) + "\n\n", "configs block")
    hdr = ("# GENERATED by scripts/kvq/prepare_glm53_kvshare_ab.py --peerkv from " + str(SOURCE) + " -- do not edit by hand.\n"
           "# gpu04 A/B on the v7 fleet config (v7 + FP8 KV + mr64 + HiCache off); engine argv is prod's on every replica.\n"
           "#   all four:        PYTORCH_CUDA_ALLOC_CONF=expandable_segments:False (legacy cudaIpc needs it)\n"
           "#   treatment r1+r2: + peerkv (GPU-to-GPU KV prefix fetch between r1 and r2; GLM53_PEERKV=0 disables),\n"
           "#                    variant suffix " + PEERKV_SUFFIX + "\n"
           "#   control   r3+r4: nothing else, variant suffix " + EXPFALSE_SUFFIX + "\n"
           "# Engine/patch embedded from scripts/kvq/peerkv/ at generation time.\n")
    return hdr + out


def main():
    ap = argparse.ArgumentParser()
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--write", action="store_true")
    g.add_argument("--check", action="store_true")
    ap.add_argument("--four", action="store_true", help="all four replicas share (host-level treatment file)")
    ap.add_argument("--hicache-off", default=None, help="arm B: comma-separated replicas without HiCache, e.g. r3,r4")
    ap.add_argument("--gpu13", action="store_true", help="arm D: gpu13 r1a+r1b share one store (small-models.yaml)")
    ap.add_argument("--v7-hicache-off-long", action="store_true", help="long arm: gpu02 r2b = v7 canary r2a without HiCache")
    ap.add_argument("--gpu13-pool", action="store_true", help="arm D': gpu13 r1a+r1b pool host cache (64 GiB L2 each + 520 GiB store)")
    ap.add_argument("--peerkv", action="store_true", help="gpu04 A/B: all v7 + HiCache off; r1+r2 + peerkv")
    ap.add_argument("--v7-hicache-off", default=None, help="arm B': replica (r3) = v7 canary r4 without HiCache")
    a = ap.parse_args()
    if not a.peerkv:
        # Historical modes (exp 31/32): built from files that the v7 fleet rollout (#348, v0.0.480)
        # replaced or deleted. Their outputs are kept as deployed records; regenerating them is not
        # possible from the current tree.
        try:
            return _main_historical(a)
        except (AssertionError, ValueError, FileNotFoundError, SystemExit) as e:
            if isinstance(e, SystemExit) and not isinstance(e.code, str):
                raise  # --check found a diff (exit 1) or success
            sys.exit(f"historical mode: its source files changed or were removed by the v7 fleet rollout (#348); "
                     f"the committed output is kept as a record and cannot be regenerated ({type(e).__name__}: {e})")
    new, path = render_peerkv(), ROOT / PEERKV_TARGET
    _write_or_check(a, new, path)


def _main_historical(a):
    if a.v7_hicache_off_long:
        new = render_v7_hicache_off("r2b", "r2a", Path("prod/GLM-5.3-Flash-SGL-TP4-W4AFP8-LongContext-V7Canary.yaml"), "L-B'")
        path = ROOT / Path("prod/GLM-5.3-Flash-SGL-TP4-W4AFP8-LongContext-V7-HiCacheOff-r2b.yaml")
    elif a.gpu13_pool:
        new, path = render_gpu13(pool=True), ROOT / Path("prod/small-models-GLM53-KVSharePool.yaml")
    elif a.v7_hicache_off:
        new, path = render_v7_hicache_off(a.v7_hicache_off), ROOT / Path("prod/GLM-5.3-Flash-SGL-TP2x4-W4AFP8-V7-HiCacheOff-r3.yaml")
    elif a.gpu13:
        new, path = render_gpu13(), ROOT / TARGET13
    elif a.hicache_off:
        reps = tuple(a.hicache_off.split(","))
        assert set(reps) <= {"r1", "r2", "r3", "r4"} and len(reps) == 2, reps
        new, path = render_hicache_off(reps), ROOT / target_off(reps)
    else:
        new = render(a.four)
        path = ROOT / (TARGET4 if a.four else TARGET)
    rel = path.relative_to(ROOT)
    if a.write:
        sys.exit(f"historical mode: refusing to overwrite {rel} (a deployed record; its sources changed in the v7 fleet rollout #348)")
    if (path.read_text() if path.exists() else "") != new:
        sys.exit(f"historical mode: {rel} no longer matches the current sources (changed by the v7 fleet rollout #348); "
                 "kept as a record, not regenerated")
    print("up to date")


def _write_or_check(a, new, path):
    if a.write:
        path.write_text(new); print(f"wrote {path.relative_to(ROOT)}"); return
    old = path.read_text() if path.exists() else ""
    if old != new:
        sys.stdout.writelines(difflib.unified_diff(old.splitlines(True), new.splitlines(True), str(path.relative_to(ROOT)), "generated"))
        sys.exit(1)
    print("up to date")


if __name__ == "__main__":
    main()
