#!/usr/bin/env python3
# How to run: python3 scripts/kvq/prepare_glm53_kvshare_ab.py --write   (or --check)
"""Generate prod/GLM-5.3-Flash-SGL-TP2x4-W4AFP8-KVShare-AB.yaml: an in-host A/B of the shared KV
host tier on one base-tier host, from the live base file prod/GLM-5.3-Flash-SGL-TP2x4-W4AFP8.yaml.

Control: r1 (GPUs 0-1) and r2 (GPUs 2-3), byte-identical to the base file.
Treatment: r3 (GPUs 4-5) and r4 (GPUs 6-7) share an L3 HiCache file tier on a tmpfs volume only
they mount (`kvshare`). The engine image is unchanged (v6); the shared-tier change is applied at
start by scripts/kvq/glm53_shared_kv_startup_patch.py (cvm-compose-files PR #304 ported to v6,
hash-checked before and after, fail closed: a mismatch stops the replica instead of serving
unpatched).

RAM is held equal between the arms: each control replica keeps its 325 GiB L2; each treatment
replica gets 250 GiB L2 plus half of a 150 GiB shared L3 store (2 x 250 + 150 = 650 GiB = 2 x 325).
The proxy, its conversation affinity and every other service are unchanged, so both arms see the
same routing. Everything the A/B reads is already exported or added by the patch:
  sglang:ghost_* (pooled prize, other-replica-only tokens per replica), sglang:kv_tier_*,
  sglang:storage_prefetch_hit_tokens_total, and sglang:kvshare_storage_hit_tokens_total{source}
  / sglang:kvshare_storage_written_tokens_total (self vs peer attribution, this patch).
Runbook: docs/glm53-kvshare-ab.md. Rollback: deploy the base file at the current tag with the
same scoped service list (r3, r4); the base file defines no `kvshare` volume, so the tmpfs store
goes with it.
"""
import argparse, difflib, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = Path("prod/GLM-5.3-Flash-SGL-TP2x4-W4AFP8.yaml")
TARGET = Path("prod/GLM-5.3-Flash-SGL-TP2x4-W4AFP8-KVShare-AB.yaml")
# Host-level variant: all four replicas share one store; another base-tier host is the control.
TARGET4 = Path("prod/GLM-5.3-Flash-SGL-TP2x4-W4AFP8-KVShare4.yaml")
PATCH = Path("scripts/kvq/glm53_shared_kv_startup_patch.py")
TREATMENT = ("r3", "r4")
VARIANT_SUFFIX = "-kvshare-l3file-v1"
SHARED_ARGS = ("--hicache-host-memory-mode cache --hicache-storage-backend file "
               "--hicache-storage-prefetch-policy wait_complete")


def one(text, old, new, label):
    n = text.count(old)
    if n != 1:
        sys.exit(f"{label}: expected 1 anchor in {SOURCE}, found {n} (base file changed; update the generator)")
    return text.replace(old, new)


def block(text, indent):
    pad = " " * indent
    return "\n".join((pad + l) if l.strip() else "" for l in text.replace("$", "$$").rstrip("\n").split("\n"))


def render(four=False):
    treatment = ("r1", "r2", "r3", "r4") if four else TREATMENT
    suffix = "-kvshare4-l3file-v1" if four else VARIANT_SUFFIX
    vol = "kvshare4" if four else "kvshare"
    store, tmpfs = ("300GiB", "320g") if four else ("150GiB", "160g")
    src = (ROOT / SOURCE).read_text()
    patch = (ROOT / PATCH).read_text()
    out = src

    # 1) Header.
    if four:
        out = ("# GENERATED by scripts/kvq/prepare_glm53_kvshare_ab.py --four from " + str(SOURCE) + " -- do not edit by hand.\n"
               "# HOST-LEVEL A/B TREATMENT: all four replicas share an L3 HiCache file tier on the `kvshare4` tmpfs\n"
               "# volume (startup patch glm53_shared_kv_startup_patch, RAM-neutral 4 x 250 + 300 GiB = 4 x 325 GiB).\n"
               "# The control is another base-tier host on the base file. Runbook: docs/glm53-kvshare-ab.md.\n"
               "# Roll one replica at a time with scoped compose/up (scripts/kvq/deploy_kvshare_ab.py --four).\n") + out
    else:
        out = ("# GENERATED by scripts/kvq/prepare_glm53_kvshare_ab.py from " + str(SOURCE) + " -- do not edit by hand.\n"
               "# IN-HOST A/B: r1+r2 = control (unchanged), r3+r4 = treatment sharing an L3 HiCache file tier on\n"
               "# the `kvshare` tmpfs volume (startup patch glm53_shared_kv_startup_patch, RAM-neutral 250+250+150 GiB).\n"
               "# Runbook: docs/glm53-kvshare-ab.md. Deploy only r3/r4 (+ nothing else) with a scoped compose/up.\n") + out

    # 2) Treatment anchor: the candidate argv, launched through the startup patch, plus the file tier.
    cand_start = out.index("x-sg-glm53-flash-candidate: &sg-glm53-flash-candidate\n")
    cmd_start = out.index("  command: >\n      sglang serve\n", cand_start)
    cmd_end = out.index("\n\n", cmd_start)
    argv = " ".join(l.strip() for l in out[cmd_start:cmd_end].splitlines()[1:])  # "sglang serve --model-path ..."
    assert argv.startswith("sglang serve --model-path"), argv[:80]
    anchor = f"""x-sg-glm53-flash-kvshare: &sg-glm53-flash-kvshare
  # Treatment arm of the in-host shared-KV A/B: the candidate argv above, started through the
  # shared-KV startup patch (exact-anchor edits of the v6 image's mem_cache files, verified by
  # sha256 before and after; any mismatch exits before serving), plus an L3 HiCache file tier on
  # the `kvshare` tmpfs volume that both treatment replicas mount.
  <<: *sg-glm53-flash-candidate
  entrypoint: ["bash", "-c"]
  command:
    - |
      python3 /etc/glm53/shared_kv_patch.py || exit 1
      exec {argv} {SHARED_ARGS}
  configs:
    - source: glm53_shared_kv_patch
      target: /etc/glm53/shared_kv_patch.py
      mode: 0444
  volumes:
    - kernel_cache:/root/.cache
    - huggingface_cache:/root/.cache/huggingface
    - ghost:/ghost
    - {vol}:/kvshared

"""
    out = out[:cmd_end + 2] + anchor + out[cmd_end + 2:]

    # 3) Treatment replicas: anchor, L2 budget, file-tier env, variant label.
    n = len(treatment)
    if four:
        budget_note = "250 GiB L2 + 1/4 of the 300 GiB shared L3 store = the base file's 325 GiB"
        share_head = ("# Shared L3 tier (all four replicas). The store is the `kvshare4` tmpfs every replica\n"
                      "# mounts; each replica's evictor is capped at MAX_SIZE (non-owner TP ranks at 0.25x\n"
                      "# for their own mamba shards), and 4 x 1.25 x 60Gi = 300Gi = the store budget.")
        vol_note = "300 GiB"
    else:  # byte-identical to the deployed 2-way file
        budget_note = "250 GiB L2 + half of the 150 GiB shared L3 store = the control's 325 GiB"
        share_head = ("# Shared L3 tier (treatment only). The store is the `kvshare` tmpfs both treatment\n"
                      "# replicas mount; each replica's evictor is capped at MAX_SIZE (non-owner TP ranks at\n"
                      "# 0.25x for their own mamba shards), and 2 x 1.25 x 60Gi = 150Gi = the store budget.")
        vol_note = "150 GiB"

    def tier_env(pad, r):
        lines = [share_head,
                 "SGLANG_HICACHE_FILE_BACKEND_STORAGE_DIR=/kvshared",
                 "# Positive-lookup cache (5 s TTL; misses fall back to a stat, so pages a peer",
                 "# just wrote are found). Without it every existence check scans the whole store.",
                 "SGLANG_HICACHE_FILE_BACKEND_ENABLE_METADATA_CACHE=1",
                 "SGLANG_HICACHE_FILE_BACKEND_MAX_SIZE=${GLM53_KVSHARE_FILE_MAX:-60Gi}",
                 f"SGLANG_HICACHE_SHARED_STORE_BUDGET=${{GLM53_KVSHARE_STORE_BUDGET:-{store}}}",
                 "# sglang:kvshare_storage_* self/peer attribution (TP rank 0).",
                 "SGLANG_KVSHARE_METRICS=1"]
        if four:
            # One INFO line per storage restore (pages, MB, seconds, MB/s): the prod measure of
            # restore cost against the gpu13 qualification (13.3-14.2 s at ~220K tokens).
            lines += ["# One INFO line per storage restore (pages, MB, s, MB/s), to compare prod restore",
                      "# cost with the gpu13 qualification (13.3-14.2 s at ~220K tokens).",
                      "SGLANG_KVSHARE_LOG_READS=1"]
        res = ""
        for l in lines:
            for sub in l.split("\n"):
                res += pad + (sub if sub.startswith("#") else "- " + sub) + "\n"
        return res

    for r in treatment:
        svc = f"  model-sg-glm53-w4afp8-tp2-{r}:\n    <<: *sg-glm53-flash-candidate\n"
        out = one(out, svc, svc.replace("*sg-glm53-flash-candidate", "*sg-glm53-flash-kvshare"), f"{r} anchor")
        s0 = out.index(f"  model-sg-glm53-w4afp8-tp2-{r}:\n")
        s1 = out.index("\n  # ---", s0) if "\n  # ---" in out[s0:] else len(out)
        body = out[s0:s1]
        if r != "r1":
            body = one(body, "      - SGLANG_HICACHE_RAM_BUDGET=${GLM53_HICACHE_RAM_BUDGET:-325GiB}\n",
                       f"      # Treatment: {budget_note}.\n"
                       "      - SGLANG_HICACHE_RAM_BUDGET=${GLM53_KVSHARE_RAM_BUDGET:-250GiB}\n", f"{r} ram budget")
            body = one(body, f"      - SGLANG_GHOST_CACHE_REPLICA={r}\n      - SGLANG_KV_TIER_METRICS=1\n",
                       f"      - SGLANG_GHOST_CACHE_REPLICA={r}\n      - SGLANG_KV_TIER_METRICS=1\n" + tier_env("      ", r),
                       f"{r} file tier env")
        body = body.replace("-strict-budget8192-obs-v1", "-strict-budget8192-obs-v1" + suffix)
        assert body.count(suffix) == 2, f"{r}: expected 2 config_variant labels"
        out = out[:s0] + body + out[s1:]
    if "r1" in treatment:
        # r1 has no environment of its own: it inherits the common anchor's list, which is
        # written for r1 (SGLANG_GHOST_CACHE_REPLICA=r1). Every service on that anchor is a GLM
        # replica, and in this file all of them override it except r1, so edit it in place.
        out = one(out, "    - SGLANG_HICACHE_RAM_BUDGET=${GLM53_HICACHE_RAM_BUDGET:-325GiB}\n",
                  f"    # Treatment (r1 inherits this list): {budget_note}.\n"
                  "    - SGLANG_HICACHE_RAM_BUDGET=${GLM53_KVSHARE_RAM_BUDGET:-250GiB}\n", "r1 ram budget")
        out = one(out, "    - SGLANG_GHOST_CACHE_REPLICA=r1\n    - SGLANG_KV_TIER_METRICS=1\n",
                  "    - SGLANG_GHOST_CACHE_REPLICA=r1\n    - SGLANG_KV_TIER_METRICS=1\n" + tier_env("    ", "r1"),
                  "r1 file tier env")

    # 4) The shared store volume (in-memory; gone when the treatment is rolled back).
    out = one(out, "  ghost:\n    driver: local\n    driver_opts:\n      type: tmpfs\n      device: tmpfs\n      o: \"size=1m,mode=0700\"\n",
              "  ghost:\n    driver: local\n    driver_opts:\n      type: tmpfs\n      device: tmpfs\n      o: \"size=1m,mode=0700\"\n"
              f"  # Shared L3 HiCache store for the treatment replicas only. Sized above the {vol_note} store\n"
              "  # budget so the evictors, not tmpfs, bound it.\n"
              f"  {vol}:\n    driver: local\n    driver_opts:\n      type: tmpfs\n      device: tmpfs\n"
              f"      o: \"size=${{GLM53_KVSHARE_TMPFS:-{tmpfs}}},mode=0700\"\n", "kvshare volume")

    # 5) The startup patch as a config.
    out = one(out, "\nconfigs:\n", "\nconfigs:\n  glm53_shared_kv_patch:\n    content: |\n" + block(patch, 6) + "\n\n", "configs block")
    return out


def main():
    ap = argparse.ArgumentParser()
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--write", action="store_true")
    g.add_argument("--check", action="store_true")
    ap.add_argument("--four", action="store_true", help="all four replicas share (host-level treatment file)")
    a = ap.parse_args()
    new = render(a.four)
    path = ROOT / (TARGET4 if a.four else TARGET)
    if a.write:
        path.write_text(new); print(f"wrote {path.relative_to(ROOT)}"); return
    old = path.read_text() if path.exists() else ""
    if old != new:
        sys.stdout.writelines(difflib.unified_diff(old.splitlines(True), new.splitlines(True), str(path.relative_to(ROOT)), "generated"))
        sys.exit(1)
    print("up to date")


if __name__ == "__main__":
    main()
