#!/usr/bin/env python3
# How to run: python3 scripts/kvq/prepare_glm53_kvshare_ab.py --write   (or --check)
"""Generate prod/GLM-5.3-Flash-SGL-TP2x4-W4AFP8-KVShare-AB.yaml: an in-host A/B of the shared KV
host tier on one base-tier host, from the live base file prod/GLM-5.3-Flash-SGL-TP2x4-W4AFP8.yaml.

Control: r1 (GPUs 0-1) and r2 (GPUs 2-3), byte-identical to the base file.
Treatment: r3 (GPUs 4-5) and r4 (GPUs 6-7) share an L3 HiCache file tier on a tmpfs volume only
they mount (`kvshare`). The engine image is unchanged (v6); the shared-tier change is applied at
start by scripts/kvq/glm53_shared_kv_startup_patch.py (cvm-compose-files PR #304 ported to v6,
hash-checked before and after, fail closed: a mismatch stops the replica instead of serving
unpatched).

RAM is held equal between the arms: each control replica keeps its 325 GiB L2; each treatment
replica gets 250 GiB L2 plus half of a 150 GiB shared L3 store (2 x 250 + 150 = 650 GiB = 2 x 325).
The proxy, its conversation affinity and every other service are unchanged, so both arms see the
same routing. Everything the A/B reads is already exported or added by the patch:
  sglang:ghost_* (pooled prize, other-replica-only tokens per replica), sglang:kv_tier_*,
  sglang:storage_prefetch_hit_tokens_total, and sglang:kvshare_storage_hit_tokens_total{source}
  / sglang:kvshare_storage_written_tokens_total (self vs peer attribution, this patch).
Runbook: docs/glm53-kvshare-ab.md. Rollback: deploy the base file at the current tag with the
same scoped service list (r3, r4); the base file defines no `kvshare` volume, so the tmpfs store
goes with it.
"""
import argparse, difflib, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = Path("prod/GLM-5.3-Flash-SGL-TP2x4-W4AFP8.yaml")
TARGET = Path("prod/GLM-5.3-Flash-SGL-TP2x4-W4AFP8-KVShare-AB.yaml")
PATCH = Path("scripts/kvq/glm53_shared_kv_startup_patch.py")
TREATMENT = ("r3", "r4")
VARIANT_SUFFIX = "-kvshare-l3file-v1"
SHARED_ARGS = ("--hicache-host-memory-mode cache --hicache-storage-backend file "
               "--hicache-storage-prefetch-policy wait_complete")


def one(text, old, new, label):
    n = text.count(old)
    if n != 1:
        sys.exit(f"{label}: expected 1 anchor in {SOURCE}, found {n} (base file changed; update the generator)")
    return text.replace(old, new)


def block(text, indent):
    pad = " " * indent
    return "\n".join((pad + l) if l.strip() else "" for l in text.replace("$", "$$").rstrip("\n").split("\n"))


def render():
    src = (ROOT / SOURCE).read_text()
    patch = (ROOT / PATCH).read_text()
    out = src

    # 1) Header.
    out = ("# GENERATED by scripts/kvq/prepare_glm53_kvshare_ab.py from " + str(SOURCE) + " -- do not edit by hand.\n"
           "# IN-HOST A/B: r1+r2 = control (unchanged), r3+r4 = treatment sharing an L3 HiCache file tier on\n"
           "# the `kvshare` tmpfs volume (startup patch glm53_shared_kv_startup_patch, RAM-neutral 250+250+150 GiB).\n"
           "# Runbook: docs/glm53-kvshare-ab.md. Deploy only r3/r4 (+ nothing else) with a scoped compose/up.\n") + out

    # 2) Treatment anchor: the candidate argv, launched through the startup patch, plus the file tier.
    cand_start = out.index("x-sg-glm53-flash-candidate: &sg-glm53-flash-candidate\n")
    cmd_start = out.index("  command: >\n      sglang serve\n", cand_start)
    cmd_end = out.index("\n\n", cmd_start)
    argv = " ".join(l.strip() for l in out[cmd_start:cmd_end].splitlines()[1:])  # "sglang serve --model-path ..."
    assert argv.startswith("sglang serve --model-path"), argv[:80]
    anchor = f"""x-sg-glm53-flash-kvshare: &sg-glm53-flash-kvshare
  # Treatment arm of the in-host shared-KV A/B: the candidate argv above, started through the
  # shared-KV startup patch (exact-anchor edits of the v6 image's mem_cache files, verified by
  # sha256 before and after; any mismatch exits before serving), plus an L3 HiCache file tier on
  # the `kvshare` tmpfs volume that both treatment replicas mount.
  <<: *sg-glm53-flash-candidate
  entrypoint: ["bash", "-c"]
  command:
    - |
      python3 /etc/glm53/shared_kv_patch.py || exit 1
      exec {argv} {SHARED_ARGS}
  configs:
    - source: glm53_shared_kv_patch
      target: /etc/glm53/shared_kv_patch.py
      mode: 0444
  volumes:
    - kernel_cache:/root/.cache
    - huggingface_cache:/root/.cache/huggingface
    - ghost:/ghost
    - kvshare:/kvshared

"""
    out = out[:cmd_end + 2] + anchor + out[cmd_end + 2:]

    # 3) Treatment replicas: anchor, L2 budget, file-tier env, variant label.
    for r in TREATMENT:
        svc = f"  model-sg-glm53-w4afp8-tp2-{r}:\n    <<: *sg-glm53-flash-candidate\n"
        out = one(out, svc, svc.replace("*sg-glm53-flash-candidate", "*sg-glm53-flash-kvshare"), f"{r} anchor")
        s0 = out.index(f"  model-sg-glm53-w4afp8-tp2-{r}:\n")
        s1 = out.index("\n  # ---", s0) if "\n  # ---" in out[s0:] else len(out)
        body = out[s0:s1]
        body = one(body, "      - SGLANG_HICACHE_RAM_BUDGET=${GLM53_HICACHE_RAM_BUDGET:-325GiB}\n",
                   "      # Treatment: 250 GiB L2 + half of the 150 GiB shared L3 store = the control's 325 GiB.\n"
                   "      - SGLANG_HICACHE_RAM_BUDGET=${GLM53_KVSHARE_RAM_BUDGET:-250GiB}\n", f"{r} ram budget")
        body = one(body, f"      - SGLANG_GHOST_CACHE_REPLICA={r}\n      - SGLANG_KV_TIER_METRICS=1\n",
                   f"      - SGLANG_GHOST_CACHE_REPLICA={r}\n      - SGLANG_KV_TIER_METRICS=1\n"
                   "      # Shared L3 tier (treatment only). The store is the `kvshare` tmpfs both treatment\n"
                   "      # replicas mount; each replica's evictor is capped at MAX_SIZE (non-owner TP ranks at\n"
                   "      # 0.25x for their own mamba shards), and 2 x 1.25 x 60Gi = 150Gi = the store budget.\n"
                   "      - SGLANG_HICACHE_FILE_BACKEND_STORAGE_DIR=/kvshared\n"
                   "      # Positive-lookup cache (5 s TTL; misses fall back to a stat, so pages a peer\n"
                   "      # just wrote are found). Without it every existence check scans the whole store.\n"
                   "      - SGLANG_HICACHE_FILE_BACKEND_ENABLE_METADATA_CACHE=1\n"
                   "      - SGLANG_HICACHE_FILE_BACKEND_MAX_SIZE=${GLM53_KVSHARE_FILE_MAX:-60Gi}\n"
                   "      - SGLANG_HICACHE_SHARED_STORE_BUDGET=${GLM53_KVSHARE_STORE_BUDGET:-150GiB}\n"
                   "      # sglang:kvshare_storage_* self/peer attribution (TP rank 0).\n"
                   "      - SGLANG_KVSHARE_METRICS=1\n", f"{r} file tier env")
        body = body.replace("-strict-budget8192-obs-v1", "-strict-budget8192-obs-v1" + VARIANT_SUFFIX)
        assert body.count(VARIANT_SUFFIX) == 2, f"{r}: expected 2 config_variant labels"
        out = out[:s0] + body + out[s1:]

    # 4) The shared store volume (in-memory; gone when the treatment is rolled back).
    out = one(out, "  ghost:\n    driver: local\n    driver_opts:\n      type: tmpfs\n      device: tmpfs\n      o: \"size=1m,mode=0700\"\n",
              "  ghost:\n    driver: local\n    driver_opts:\n      type: tmpfs\n      device: tmpfs\n      o: \"size=1m,mode=0700\"\n"
              "  # Shared L3 HiCache store for the treatment replicas only. Sized above the 150 GiB store\n"
              "  # budget so the evictors, not tmpfs, bound it.\n"
              "  kvshare:\n    driver: local\n    driver_opts:\n      type: tmpfs\n      device: tmpfs\n"
              "      o: \"size=${GLM53_KVSHARE_TMPFS:-160g},mode=0700\"\n", "kvshare volume")

    # 5) The startup patch as a config.
    out = one(out, "\nconfigs:\n", "\nconfigs:\n  glm53_shared_kv_patch:\n    content: |\n" + block(patch, 6) + "\n\n", "configs block")
    return out


def main():
    ap = argparse.ArgumentParser()
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--write", action="store_true")
    g.add_argument("--check", action="store_true")
    a = ap.parse_args()
    new = render()
    path = ROOT / TARGET
    if a.write:
        path.write_text(new); print(f"wrote {TARGET}"); return
    old = path.read_text() if path.exists() else ""
    if old != new:
        sys.stdout.writelines(difflib.unified_diff(old.splitlines(True), new.splitlines(True), str(TARGET), "generated"))
        sys.exit(1)
    print("up to date")


if __name__ == "__main__":
    main()
