#!/usr/bin/env python3
"""Generate the r2-only HiCache canary file after the signed image has been published.

The canonical compose file (COMPOSE) is source-only and is never modified by
this script. `--write` regenerates CANDIDATE and RELEASE from COMPOSE; with no
flags it previews the diff. `--check` verifies the committed CANDIDATE is
still exactly what this script would generate from the committed COMPOSE and
RELEASE.
"""
import argparse
import difflib
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
COMPOSE = Path('prod/GLM-5.3-Flash-SGL-TP4.yaml')
CANDIDATE = Path('prod/GLM-5.3-Flash-SGL-TP4-HiCache.yaml')
RELEASE = Path('docker/sglang-glm53-hicache/RELEASED_IMAGE')
VARIANT = 'fc91d24-hicache-cuda-host-pooled-v1-h200-tp4-ep4-eagle-adaptive-5-1-6-strict-budget8192'
OPTIONS = {
    '--hicache-write-policy': 'write_through',
    '--hicache-io-backend': 'direct',
    '--hicache-mem-layout': 'page_first_direct',
}
ENVIRONMENT = {
    'SGLANG_HICACHE_RAM_BUDGET': '${GLM53_HICACHE_RAM_BUDGET:-80%}',
    'SGLANG_HICACHE_CUDA_HOST_MEMORY': '${GLM53_HICACHE_CUDA_HOST_MEMORY:-1}',
    'SGLANG_HICACHE_POOLED_TRANSFERS': '1',
    'SGLANG_HICACHE_STAGING_PAGES': '64',
}
HEADER = (
    '# This is the HiCache canary variant of prod/GLM-5.3-Flash-SGL-TP4.yaml,\n'
    '# generated by scripts/prepare_glm53_hicache_canary.py. r1 is the unchanged\n'
    '# control; r2 uses the signed HCC-safe HiCache image with CUDA-owned host\n'
    '# memory (cudaMallocHost, no cudaHostRegister, no Unified Memory). Deploy\n'
    '# this file only on hosts explicitly selected for the HiCache canary; every\n'
    '# other host keeps prod/GLM-5.3-Flash-SGL-TP4.yaml. Do not hand-edit —\n'
    '# regenerate with this script.\n'
)


def candidate(text, image):
    if not re.fullmatch(r'docker\.io/nearaidev/sglang@sha256:[a-f0-9]{64}', image):
        raise ValueError('Require the immutable docker.io/nearaidev/sglang digest from the signed publishing workflow')
    if '--enable-hierarchical-cache' in text or 'SGLANG_HICACHE_' in text:
        raise ValueError('Canonical compose already has a HiCache configuration; review it explicitly')
    start = text.index('x-sg-glm53-flash-common:')
    end = text.index('\nx-dcgm-common:', start)
    common = text[start:end]
    if f'  image: {image}\n' in common:
        raise ValueError('The control image does not contain the HiCache patch')
    command = common[common.index('  command: >'):common.index('  volumes:')]
    environment = common[common.index('  environment:'):common.index('  restart:')]
    command = ''.join('  ' + line if line.strip() else line for line in command.splitlines(True))
    command += '        --enable-hierarchical-cache\n'
    command += ''.join(f'        {key} {value}\n' for key, value in OPTIONS.items())
    environment = ''.join('  ' + line if line.strip() else line for line in environment.splitlines(True))
    environment += ''.join(f'      - {key}={value}\n' for key, value in ENVIRONMENT.items())
    start = text.index('  model-sg-glm53-fp8-tp4-r2:\n')
    end = text.index('\n  # Explicit operator-only semantic check;', start)
    service = text[start:end]
    insertion = '    container_name: model-sg-glm53-fp8-tp4-r2\n'
    if service.count(insertion) != 1 or '    image:' in service or '    command:' in service:
        raise ValueError('Unrecognized r2 service shape; refusing to overwrite overrides')
    service = service.replace(insertion, insertion + f'    image: {image}\n' + command + environment)
    original_variant = 'official-upstream-fc91d24-h200-tp4-ep4-eagle-adaptive-5-1-6-strict-budget8192'
    if service.count(original_variant) != 2:
        raise ValueError('Unrecognized r2 telemetry variant')
    service = service.replace(original_variant, VARIANT)
    text = text[:start] + service + text[end:]
    start = text.index('              - job_name: sglang-model-sg-glm53-fp8-tp4-r2\n')
    end = text.index('              - job_name:', start + 1)
    scrape = text[start:end]
    if scrape.count(original_variant) != 1:
        raise ValueError('Unrecognized r2 scrape labels')
    text = text[:start] + scrape.replace(original_variant, VARIANT) + text[end:]
    return HEADER + text


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--image', help='Signed docker.io/nearaidev/sglang@sha256:... digest')
    parser.add_argument('--write', action='store_true', help='Write CANDIDATE and RELEASE (never modifies COMPOSE)')
    parser.add_argument('--check', action='store_true',
                         help='Exit non-zero with a diff if the committed CANDIDATE is out of sync')
    parser.add_argument('--force', action='store_true',
                         help='With --write, replace a RELEASED_IMAGE that already records a different digest')
    args = parser.parse_args()

    if args.check:
        if args.image or args.write or args.force:
            parser.error('--check cannot be combined with --image, --write or --force')
        canonical = (ROOT / COMPOSE).read_text()
        if not (ROOT / RELEASE).exists():
            print(f'{RELEASE} is missing')
            raise SystemExit(1)
        released_image = (ROOT / RELEASE).read_text().strip()
        try:
            expected = candidate(canonical, released_image)
        except ValueError as err:
            print(f'{RELEASE} is not a valid signed image digest: {err}')
            raise SystemExit(1)
        actual = (ROOT / CANDIDATE).read_text() if (ROOT / CANDIDATE).exists() else ''
        if actual != expected:
            print(''.join(difflib.unified_diff(actual.splitlines(True), expected.splitlines(True),
                                              fromfile='a/' + str(CANDIDATE), tofile='b/' + str(CANDIDATE))), end='')
            raise SystemExit(1)
        return

    if not args.image:
        parser.error('--image is required unless --check is given')
    if args.write and (ROOT / RELEASE).exists():
        recorded = (ROOT / RELEASE).read_text().strip()
        if recorded != args.image and not args.force:
            parser.error(f'{RELEASE} already records {recorded}; pass --force to replace it')
    canonical = (ROOT / COMPOSE).read_text()
    updated = candidate(canonical, args.image)
    for name, before, after in (
        (CANDIDATE, (ROOT / CANDIDATE).read_text() if (ROOT / CANDIDATE).exists() else '', updated),
        (RELEASE, (ROOT / RELEASE).read_text() if (ROOT / RELEASE).exists() else '', args.image + '\n'),
    ):
        print(''.join(difflib.unified_diff(before.splitlines(True), after.splitlines(True),
                                          fromfile='a/' + str(name), tofile='b/' + str(name))), end='')
        if args.write:
            (ROOT / name).write_text(after)


if __name__ == '__main__':
    main()
